CREATE TABLE [dbo].[TodoCollections]
(
    [Id] INT IDENTITY(1,1),
    [UserId] INT NOT NULL,
    [Name] NVARCHAR(512) NOT NULL,
    [CreatedOn] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [IsCompleted] BIT NOT NULL DEFAULT 0,
    [IsDeleted] BIT NOT NULL DEFAULT 0,
    
    CONSTRAINT PK_Todos PRIMARY KEY CLUSTERED (Id),
    CONSTRAINT FK_Todos_Users FOREIGN KEY (UserId) REFERENCES [dbo].[Users](Id)
)